/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as battleshipSol from "./Battleship.sol";
export type { battleshipSol };
import type * as verifySol from "./Verify.sol";
export type { verifySol };
export * as factories from "./factories";
export type { BattleShipGame } from "./Battleship.sol/BattleShipGame";
export { BattleShipGame__factory } from "./factories/Battleship.sol/BattleShipGame__factory";
export type { SigVerifier } from "./Verify.sol/SigVerifier";
export { SigVerifier__factory } from "./factories/Verify.sol/SigVerifier__factory";
